/**
 * AI-Free Code Detection System (Heuristic & Behavior Based)
 * 
 * This module calculates a probability score (0-100) that code was generated by AI.
 * It uses behavioral metrics (provided by frontend) and static code analysis.
 * 
 * NOTE: This is a probabilistic estimation, not a definitive proof.
 */

const calculateAIScore = (code, metadata) => {
    let score = 0;
    const heuristics = [];
    const { 
        pasteCount = 0, 
        timeSpentMs = 0, 
        totalKeyPresses = 0 
    } = metadata;

    const codeLength = code.length;

    // --- 1. PASTE DETECTION (High Weight) ---
    // Rule: If the user pasted code, suspicion rises.
    if (pasteCount > 0) {
        score += 20;
        heuristics.push('Paste event detected (+20)');

        // Rule: Instant Full Paste (Large code, minimal time, single paste)
        if (codeLength > 100 && timeSpentMs < 10000 && pasteCount === 1) {
            score += 50;
            heuristics.push('Instant large paste (+50)');
        }
    }

    // --- 2. TYPING SPEED ANALYSIS (High Weight) ---
    // Rule: Superhuman typing speed.
    // Average coder: 30-60 WPM (words per minute). 1 word ~ 5 chars.
    // Suspicious: > 150 WPM sustained.
    if (timeSpentMs > 0 && codeLength > 50) {
        const minutes = timeSpentMs / 60000;
        const cpm = codeLength / minutes; // Characters Per Minute

        if (cpm > 800) { // ~160 WPM
            score += 40;
            heuristics.push(`Superhuman typing speed: ${Math.round(cpm)} CPM (+40)`);
        } else if (cpm > 500) { // ~100 WPM
            score += 20;
            heuristics.push(`High typing speed: ${Math.round(cpm)} CPM (+20)`);
        }
    }

    // --- 3. KEYPRESS RATIO (Medium Weight) ---
    // Rule: Code length usually matches keypresses (roughly).
    // If keypresses are significantly lower than code length, implies automated insertion.
    if (totalKeyPresses > 0 && codeLength > 100) {
        const ratio = totalKeyPresses / codeLength;
        if (ratio < 0.2) { // Less than 20% of chars were typed
            score += 30;
            heuristics.push('Low keypress-to-code ratio (+30)');
        }
    }

    // --- 4. STATIC CODE PATTERNS (Low/Medium Weight) ---
    // Rule: Check for common AI formatting quirks.
    
    // a. "Here is the code" or typical AI comments
    if (code.includes('Here is the solution') || 
        code.includes('generated by AI') || 
        code.includes('certainly!')) {
        score += 80;
        heuristics.push('Detected AI conversational phrases (+80)');
    }

    // b. Over-commenting (AI tends to verify every step)
    const commentCount = (code.match(/\/\//g) || []).length;
    const lines = code.split('\n').length;
    if (lines > 10 && commentCount > lines * 0.5) {
        score += 15;
        heuristics.push('Excessive commenting density (+15)');
    }

    // --- CLAMP SCORE ---
    // Ensure score is between 0 and 100
    score = Math.min(Math.max(score, 0), 100);

    return {
        score,
        details: heuristics
    };
};

module.exports = { calculateAIScore };
